
# This is a basic workflow to help you get started with Actions

name: HTML Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
defaults:
  run:
    working-directory: florist-celeber/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Tests:
    env:
      ASSETS_PATH: assets/
      IMAGES_PATH: assets/images/
      STYLES_PATH: assets/style/
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Update apt sources
        run: sudo apt update
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install --global capture-website-cli
  
        #Because of the way the screenshot is taken we can neither set hover nor pointer attributes and therefore the easiest way to fix it is to just remove the element
      - name: Main Page screenshot (Desktop)
        run: capture-website index.html --output=../views/MainPage.png --full-page --overwrite --delay=2 --userAgent="Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0" --height=1440 --width=2560
        
      - name: Main Page screenshot (Iphone X)
        run: capture-website index.html --output=../views/MainPagePhoneX.png --emulate-device="iPhone X" --full-page --delay=2 --overwrite

      - name: Main Page screenshot (Pixel 2)
        run: capture-website index.html --output=../views/MainPagePixel2.png --emulate-device="Pixel 2" --full-page --delay=2 --overwrite
        
      - name: Kiruna Page screenshot (Desktop)
        run: capture-website kiruna/index.html --output=../views/KirunaPage.png --full-page --overwrite --delay=2 --userAgent="Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0" --height=1440 --width=2560
        
      - name: Kiruna Page screenshot (Iphone X)
        run: capture-website kiruna/index.html --output=../views/KirunaPhoneX.png --emulate-device="iPhone X" --full-page --delay=2 --overwrite

      - name: Kiruna Page screenshot (Pixel 2)
        run: capture-website kiruna/index.html --output=../views/KirunaPagePixel2.png --emulate-device="Pixel 2" --full-page --delay=2 --overwrite
        
      - name: HTML to Image desktop Våra frisörer
        run: capture-website lulea/index.html --output=../views/LuleaPage.png --full-page --overwrite --delay=2 --userAgent="Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0" --height=1440 --width=2560
        
      - name: HTML to Image Iphone X Våra frisörer
        run: capture-website lulea/index.html --output=../views/LuleaPagePhoneX.png --emulate-device="iPhone X" --full-page --delay=2 --overwrite

      - name: HTML to Image Pixel 2 Våra frisörer
        run: capture-website lulea/index.html --output=../views/LuleaPagePixel2.png --emulate-device="Pixel 2" --full-page --delay=2 --overwrite

      - name: Commit files that has been changed
        run: |
          git config --local user.name "Github Push Bot"
          git rm --cached -r ../views
          git add ../views
          git commit --allow-empty --quiet -m "Updating the repository with new generated image website view"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
